apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldb
  labels:
    app: techchallenge
    tier: backend
spec:
  selector:
    matchLabels:
      app: techchallenge
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: techchallenge
        tier: backend
    spec:
      containers:
        - image: diogomuniz/techchallenge-mysql:v3
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: secret
            - name: MYSQL_DATABASE
              value: dbpostech
            - name: MYSQL_PASSWORD
              value: secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
