apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacaoweb
  labels:
    app: techchallenge
    tier: frontend
spec:
  selector:
    matchLabels:
      app: techchallenge
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: techchallenge
        tier: frontend
    spec:
      containers:
        - name: webserver
          image: diogomuniz/techchallenge-aplicacao:v3
          ports:
            - containerPort: 80
